server:
  port: 8000
  context-path: /api

management:
  server:
    servlet:
      context-path: /actuator

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/start-wars
      exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

app:
  aplication-name: api-start-wars
  api:
    start-wars:
      uri: https://swapi.co/api/
